# Generated by Django 3.1 on 2020-09-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnapp', '0010_auto_20200929_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='identifier',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
