# Generated by Django 3.1 on 2020-09-28 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hnapp', '0004_auto_20200928_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hnapp.comment'),
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
