# Generated by Django 3.1 on 2020-09-28 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hnapp', '0007_auto_20200929_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='parent',
        ),
    ]
