# Generated by Django 3.1 on 2020-09-28 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hnapp', '0008_auto_20200929_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cooments', to='hnapp.post'),
        ),
    ]
