# Generated by Django 3.1 on 2020-09-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnapp', '0011_comment_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='votes',
            field=models.IntegerField(null=True),
        ),
    ]
