# Generated by Django 3.1 on 2020-09-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnapp', '0012_auto_20200929_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='votes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
